### ISSUE TITLE
Cannot import name 'app' from 'diffusion_webui'

### ISSUE THREAD

**Issue by WorkMujtabaAI** [kadirnar/Stable-Diffusion-ControlNet-WebUI#3]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], [line 1]
----> from diffusion_webui import app
         app()
ImportError: cannot import name 'app' from 'diffusion_webui'

there is no app in "diffusion_webui", I have checked from my local conda version also.

**Comment by kadirnar** [comment]
I am no longer developing this library.
